### ISSUE TITLE
Locale: change in city errors

### ISSUE THREAD

**Issue by wbazant** [falling-fruit/falling-fruit#129]
Turkish locale has a duplicated %{type}%{city} showing up, traditional Chinese has a funny ％ instead of %.

wbazant@wbazant-19-01:~/dev/falling-fruit-web$ grep change_in_city ../falling-fruit/config/locales/*
../falling-fruit/config/locales/ar.yml:    change_in_city: "%{type} في %{city}"
../falling-fruit/config/locales/de.yml:    change_in_city: "%{type} in %{city}"
../falling-fruit/config/locales/el.yml:    change_in_city: "%{type} σε %{city}"
../falling-fruit/config/locales/en.yml:    change_in_city: "%{type} in %{city}"
../falling-fruit/config/locales/es.yml:    change_in_city: "%{type} en %{city}"
../falling-fruit/config/locales/fr.yml:    change_in_city: "%{type} à %{city}"
../falling-fruit/config/locales/he.yml:    change_in_city: "%{type} ב %{city}"
../falling-fruit/config/locales/it.yml:    change_in_city: "%{type} in %{city}"
../falling-fruit/config/locales/nl.yml:    change_in_city: "%{type} in %{city}"
../falling-fruit/config/locales/pl.yml:    change_in_city: "%{type} w %{city}"
../falling-fruit/config/locales/pt-BR.yml:    change_in_city: "%{type} em %{city}"
../falling-fruit/config/locales/sk.yml:    change_in_city: "%{type} v %{city}"
../falling-fruit/config/locales/sv.yml:    change_in_city: "%{type} i %{city}"
../falling-fruit/config/locales/tr.yml:    change_in_city: "%{type}%{city} içinde %{type}%{city}"
../falling-fruit/config/locales/uk-UA.yml:    change_in_city: "%{type} у %{city}"
../falling-fruit/config/locales/vi.yml:    change_in_city: "%{type} ở %{city}"
../falling-fruit/config/locales/zh-CN.yml:    change_in_city: "%{type}在%{city}"
../falling-fruit/config/locales/zh-TW.yml:    change_in_city: "％{type}在％{city}"

**Comment by ezwelty** [comment]
Fixed in https://github.com/falling-fruit/falling-fruit/commit/2af28916d72131ad1c4d9a3a03381fdcd4d6bc9f.
