### ISSUE TITLE
List (multiple) selected types at top of results

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit#14]
Sorting works properly with a single selected type:

http://localhost:3100/api/0.2/locations.json?api_key=EEQRBBUB&locale=en&muni=1&nelat=40.00156699355835&nelng=-105.27841178077733&swlat=40.00084067298544&swlng=-105.28098670143163&t=198

But fails to sort results properly for multiple selected types:

http://localhost:3100/api/0.2/locations.json?api_key=EEQRBBUB&locale=en&muni=1&nelat=40.00156699355835&nelng=-105.27841178077733&swlat=40.00084067298544&swlng=-105.28098670143163&t=198,136

**Comment by dbalatero** [comment]
@ezwelty How should the sort work exactly? Currently it seems to be implemented like this:

https://github.com/falling-fruit/falling-fruit/blob/ed5aad8739eee8e4e6d30cf88787724b1fe630b7/api/locations.js#L189-L196

```js
  if (req.query.t) {
    var tids = __.map(req.query.t.split(","), function(x) {
      return parseInt(x)
    });

    sorted = "CASE WHEN array_agg(t.id) @> ARRAY["
      + tids + "] THEN 0 ELSE 1 END as sort";
  }
```

Basically if the `type_id` matches, it gives the `sort` field a `1` value, otherwise it gives it a `0`. This is why things are coming back in random order.

Can you define what a proper sort should look like so I can think about how to implement it correctly? Thanks!

**Comment by ezwelty** [comment]
@dbalatero Hmm, the spirit of that code is correct, but it doesn't seem to be working properly.

### Single type (`t=198`) WORKING

> http://localhost:3100/api/0.2/locations.json?api_key=EEQRBBUB&locale=en&muni=1&nelat=40.00156699355835&nelng=-105.27841178077733&swlat=40.00084067298544&swlng=-105.28098670143163&t=198

Locations with type_ids that include 198 are returned at top, with `sort: 0`.

```json
[12, 12, {
	"id": 139139,
	"lat": 40.0015336092,
	"lng": -105.280978381,
	"unverified": true,
	"type_ids": [198],
	"description": "[1x] Pinyon Pine @ 790 Lincoln Pl",
	"author": "City of Boulder Urban Forestry",
	"type_names": ["Pinyon pine"],
	"sort": 0
}, {
	"id": 139140,
	"lat": 40.0015618204,
	"lng": -105.280978864,
	"unverified": true,
	"type_ids": [198],
	"description": "[1x] Pinyon Pine @ 790 Lincoln Pl",
	"author": "City of Boulder Urban Forestry",
	"type_names": ["Pinyon pine"],
	"sort": 0
}, {
	"id": 132384,
	"lat": 40.0009773448,
	"lng": -105.279969576,
	"unverified": false,
	"type_ids": [252],
	"description": "[1x] Honeylocust @ 747 10th St",
	"author": "City of Boulder Urban Forestry",
	"type_names": ["Honey locust"],
	"sort": 1
}, {
       ...
}]
```

### Multiple types (`t=198,136`) NOT WORKING

> http://localhost:3100/api/0.2/locations.json?api_key=EEQRBBUB&locale=en&muni=1&nelat=40.00156699355835&nelng=-105.27841178077733&swlat=40.00084067298544&swlng=-105.28098670143163&t=198,136

Locations are returned in random order, as all have `sort: 1`. The correct behavior would be for locations with type_ids including 198 or 136 returned at top, with `sort: 0`.

```json
[12, 12, {
	"id": 129898,
	"lat": 40.0010664783,
	"lng": -105.279969289,
	"unverified": false,
	"type_ids": [253],
	"description": "[1x] Littleleaf Linden @ 751 10th St",
	"author": "City of Boulder Urban Forestry",
	"type_names": ["Small-leaved linden"],
	"sort": 1
}, {
	"id": 131677,
	"lat": 40.0011545225,
	"lng": -105.279969782,
	"unverified": false,
	"type_ids": [253],
	"description": "[1x] Littleleaf Linden @ 751 10th St",
	"author": "City of Boulder Urban Forestry",
	"type_names": ["Small-leaved linden"],
	"sort": 1
}, {
	"id": 132384,
	"lat": 40.0009773448,
	"lng": -105.279969576,
	"unverified": false,
	"type_ids": [252],
	"description": "[1x] Honeylocust @ 747 10th St",
	"author": "City of Boulder Urban Forestry",
	"type_names": ["Honey locust"],
	"sort": 1
}, {
        ...
}]
```
