### ISSUE TITLE
types.json API issues

### ISSUE THREAD

**Issue by dbalatero** [falling-fruit/falling-fruit#15]
"name" is now jus the (en) common name, not the full name "Common name [Scientific name]" (as needed by the type selectors). Such a field can be added client-side to the data once downloaded.

**Comment by dbalatero** [comment]
@ezwelty just to be clear on this: should I update a field to have "Common name [Scientific name]" instead, or add an additional field for that?

**Comment by ezwelty** [comment]
@dbalatero types.json already returns common name fields and `scientific_name`. This is a reminder to generate a locale-specific full name – <Localized common name, or English common name if not available> <[Scientific name] (if available)> – in the mobile app.

So this belongs under falling-fruit-mobile. Is there a way to transfer an issue to another repo?

**Comment by dbalatero** [comment]
@ezwelty I've moved this to https://github.com/falling-fruit/falling-fruit-mobile/issues/6
