### ISSUE TITLE
silly group by in PagesController.data

### ISSUE THREAD

**Issue by lelelelemon** [falling-fruit/falling-fruit#27]
The queries 
SELECT COALESCE(types.name) as cname, types.id, scientific_name, scientific_synonyms, usda_symbol, wikipedia_url, fruitipedia_url, urban_mushrooms_url, foraging_texas_url, eat_the_weeds_url, name, synonyms, pending, category_mask, count(*) FROM "locations" LEFT OUTER JOIN types ON types.id=ANY(locations.type_ids) GROUP BY cname, types.id, scientific_name, scientific_synonyms, usda_symbol, wikipedia_url, fruitipedia_url, urban_mushrooms_url, foraging_texas_url, eat_the_weeds_url, name, synonyms, pending, category_mask ORDER BY cname 
is quite time-consuming, and since "scientific_name, scientific_synonyms, usda_symbol, wikipedia_url, fruitipedia_url, urban_mushrooms_url, foraging_texas_url, eat_the_weeds_url, name, synonyms, pending, category_mask" can identify the location, so it's possible to use id as group condition:
SELECT COALESCE(types.name) as cname, types.id, scientific_name, scientific_synonyms, usda_symbol, wikipedia_url, fruitipedia_url, urban_mushrooms_url, foraging_texas_url, eat_the_weeds_url, name, synonyms, pending, category_mask, count(*) FROM "locations" LEFT OUTER JOIN types ON types.id=ANY(locations.type_ids) GROUP BY types.id, id order by cname;

**Comment by ezwelty** [comment]
@lelelelemon Good catch! Since this query is for counting the total instances of each type in use, grouping by `types.id` is sufficient.
