### ISSUE TITLE
join on any is not efficient

### ISSUE THREAD

**Issue by lelelelemon** [falling-fruit/falling-fruit#28]
SELECT types.id FROM "locations" LEFT OUTER JOIN types ON types.id = ANY(locations.type_ids) GROUP BY types.id
Instead of using types.id = ANY(locations.type_ids) as the join condition, we use subqueries like this:
SELECT count(distinct types.id) from types where types.id IN (select unnest(locations.type_ids) from locations);
Which will not execute types.id = ANY(locations.type_ids) for each types and each locations

**Comment by ezwelty** [comment]
Here is the ActiveRecord syntax that I got to work (from `app/views/pages/about.html.erb`):

```ruby
# unique id
Type.where(:id => Location.select("unnest(type_ids)")).select(:id).count
# non-unique id
Type.where(:id => Location.select("unnest(type_ids)")).select("distinct(id)").count
```

And you're right, it is twice as fast as the original:

```ruby
Location.
  joins("LEFT OUTER JOIN types ON types.id = ANY(locations.type_ids)").
  select("types.id").group("types.id").length
```

But when selecting locations, not types, I'm at a loss how to apply this principle. For example, from `Rakefile`, how do we get `types.category_mask` without a join-on-any?:

```ruby
cat_mask = array_to_mask(Type::DefaultCategories, Type::Categories)
ActiveRecord::Base.connection.execute(
  "SELECT *
  FROM locations INNER JOIN types ON types.id=ANY(locations.type_ids)
  WHERE (types.category_mask & #{cat_mask})>0"
)
```

Or from `app/views/pages/data.html.erb`, how do we count locations without a join on any?:

```ruby
i18n_name_field = I18n.locale != :en ?
  "types.#{I18n.locale.to_s.tr("-","_")}_name," : ""
Location.
  joins("LEFT OUTER JOIN types ON types.id=ANY(locations.type_ids)").
  select("COALESCE(#{i18n_name_field}types.name) as cname, types.id, count(*)").
  group("cname, types.id").
  order("cname")
```

**Comment by lelelelemon** [comment]
cat_mask = array_to_mask(Type::DefaultCategories, Type::Categories)
ActiveRecord::Base.connection.execute(
  "SELECT *
  FROM locations INNER JOIN types ON types.id=ANY(locations.type_ids)
  WHERE (types.category_mask & #{cat_mask})>0"
)
could be changd to this:
     lids = ActiveRecord::Base.connection.execute("select distinct(n2.id) from types join (select (unnest(locations.type_ids))
     as uid, id from locations) 
     n2 on types.id = n2.uid AND (types.category_mask & #{cat_mask})").collect{|row| row['id']}.join(",")
     cat_mask = array_to_mask(Type::DefaultCategories,Type::Categories)
     r = ActiveRecord::Base.connection.execute("SELECT locations.id, array_to_string(type_ids,':') as types, access,
       description, lat, lng, address, unverified,
       season_start, season_stop, no_season, access, unverified, author, import_id, locations.created_at, locations.updated_at
       FROM locations where id IN (#{lids})>")

**Comment by ezwelty** [comment]
@lelelelemon We now export all types and locations, so no more join-on-any in `Rakefile` (https://github.com/falling-fruit/falling-fruit/commit/43594a959d9bd666555b542d6618a8cbe5909509). That said, I did test speed and found no speed gains, which I suspect is due to the fact that `lids` is over one million entries long (see https://github.com/falling-fruit/falling-fruit/issues/29#issuecomment-323239813).
