### ISSUE TITLE
Any other issue database?

### ISSUE THREAD

**Issue by lelelelemon** [falling-fruit/falling-fruit#30]
Hi, 

Is there any other issue database for Falling-fruit except this one on github, it seems that the number of issues is relatively small here.

**Comment by ezwelty** [comment]
@lelelelemon Thanks for raising issues, I'll try to take a look tonight. Up to recently, conversations happened on a (now massive and sprawling) Trello board. I'm now gradually parsing through Trello cards and moving relevant ones to GitHub to make it easier for folks like you to jump in and help.
