### ISSUE TITLE
Map labels are always in English

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit#32]
No matter the selected locale, label text is always in English (en). For example:

https://fallingfruit.org/?z=17&y=40.65055&x=22.94020&m=true&t=roadmap&l=true&locale=el&c=forager,freegan

![image](https://user-images.githubusercontent.com/377523/29444861-33e74af6-83a0-11e7-9a78-adaa9c2a89b9.png)

**Comment by yann120** [comment]
Is this issue fixed ? Because I can't reproduce it, I can have the name of the trees in french 😄

**Comment by ezwelty** [comment]
Strange, I just tested it now on the website and labels are still showing up in English for Greek (`locale=el`), Dutch (`nl`), and Portuguese (`pt-br`), but working for the other languages (including French). Despite that the right translated name appears in both the type filter dropdown and the infowindow once the location is clicked.

Oh, I smell an API bug...
