### ISSUE TITLE
Remove Gratipay link from about page

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit#55]
Gratipay is sadly closing shop. See https://gratipay.news/the-end-cbfba8f50981

**Comment by tjbutler003** [comment]
I deleted four lines that I believe pertained to GratiPay, but do not know how to easily test to see if this made the changes I was hoping it would make.

**Comment by ezwelty** [comment]
Thanks! You missed some markup, which I removed in subsequent commit https://github.com/falling-fruit/falling-fruit/commit/39d40b8aec2d19b5e86cb96947d1bf3b50cbee5f. 

It is helpful to give maintainers access to pull requests from forks so that any needed changes can be made easily to that branch before merging:
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/. 

It is very helpful to include the issue number in your commit message or pull request – for example, "#55" – for automagical GitHub cross-referencing.

**Comment by tjbutler003** [comment]
Thanks for the suggestions, I will make sure to do those in future!
T.J.
