### ISSUE TITLE
Update list of French translators

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit#59]
Add Laura Clabé and Salomé Martin to the list of [translators](https://github.com/falling-fruit/falling-fruit/blob/39d40b8aec2d19b5e86cb96947d1bf3b50cbee5f/app/views/pages/about.html.erb#L160). They contributed to the French (Français) translation.

**Comment by SeanBarber** [comment]
Hello @ezwelty, I would like to help. I am trying to find where the list is to add the name. Is it falling-fruit/app/views/pages/about.html.erb?

**Comment by ezwelty** [comment]
Hi @SeanBarber, thanks for offering to help! My apologies for leaving out such crucial information, I've updated my original post with a link to the exact location in the code.

**Comment by SeanBarber** [comment]
Thank you! I sent a pull request.
