### ISSUE TITLE
Adding NOT NULL constraints to DB

### ISSUE THREAD

**Issue by whoisutsav** [falling-fruit/falling-fruit#68]
Hi,

There are a few model fields with presence constraints, but in the DB, the fields are nullable.

1) [Changes - description](https://github.com/falling-fruit/falling-fruit/blob/b56c3952fe7b8ead410191edf36c40a890ed2faf/app/models/change.rb#L8)
2) [Import - name](https://github.com/falling-fruit/falling-fruit/blob/b56c3952fe7b8ead410191edf36c40a890ed2faf/app/models/import.rb#L4)
3) [Problem - email](https://github.com/falling-fruit/falling-fruit/blob/b56c3952fe7b8ead410191edf36c40a890ed2faf/app/models/problem.rb#L10)

Found them using a program analyzer we're developing as part of a research project. I'm happy to share more details about it if you're interested.

Anyway, just some small improvements. In case you're interested (and think it's worthwhile) I've created a pull request. Thanks and take care.

**Comment by ezwelty** [comment]
Thank you for deploying your program analyzer on our code. Good catch! Much appreciated. I've merged your pull request (https://github.com/falling-fruit/falling-fruit/pull/69).
