### ISSUE TITLE
Location reporting form not displayed

### ISSUE THREAD

**Issue by ezwelty** [falling-fruit/falling-fruit#82]
Clicking on the `report` button in the location infowindow no longer displays the report form (as of 2020-08-17). This was reproduced in Chrome and Safari, both logged in and logged out. In Firefox, the button itself is not displayed unless logged in, in which case the result is the same.

**Comment by yann120** [comment]
Hey @ezwelty, I tried to reproduce in production, but it works fine for me
The steps that I did : find a point on the map (for me in Paris), click on it (it open the informations), and then click on report.
I can see the report button, can click on it and I successfully submit a report 😄

**Comment by ezwelty** [comment]
My apologies, this was closed by recent commits https://github.com/falling-fruit/falling-fruit/commit/0565981a06bf99d4bd5e5d335679b4438a661652 to https://github.com/falling-fruit/falling-fruit/commit/ae723fd779a68f9117d42157dcd16a7af7655fcc, but I forgot to close the associated issue. All other open issues should still be relevant...
